version: "2"

networks:
 test:

volumes:
  peer0.client1.zuelligpharma.com:
  peer1.client1.zuelligpharma.com:

services:
  peer0.client1.zuelligpharma.com:
    container_name: peer0.client1.zuelligpharma.com
    image: hyperledger/fabric-peer:2.2
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=test_net_test
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_PEER_ID=peer0.client1.zuelligpharma.com
      - CORE_PEER_ADDRESS=104.43.112.78:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.client1.zuelligpharma.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.client1.zuelligpharma.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.client1.zuelligpharma.com:8051
      - CORE_PEER_LOCALMSPID=client1MSP
      - CORE_OPERATIONS_LISTENADDRESS=peer0.client1.zuelligpharma.com:17051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.client1.zuelligpharma.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
      - couchdb0.client1.zuelligpharma.com
    volumes:
      - /var/run/:/host/var/run/
      - /home/azureuser/organizations1/peerOrganizations/client1.zuelligpharma.com/peers/peer0.client1.zuelligpharma.com/msp:/etc/hyperledger/fabric/msp
      - /home/azureuser/organizations1/peerOrganizations/client1.zuelligpharma.com/peers/peer0.client1.zuelligpharma.com/tls:/etc/hyperledger/fabric/tls
      # - /home/azureuser/crypto-config/peer0/msp:/etc/hyperledger/fabric/msp
      # - /home/azureuser/crypto-config/peer0/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 17051:17051
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    networks:
      - test
  peer1.client1.zuelligpharma.com:
    container_name: peer1.client1.zuelligpharma.com
    image: hyperledger/fabric-peer:2.2
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=test_net_test
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_PEER_ID=peer1.client1.zuelligpharma.com
      - CORE_PEER_ADDRESS=104.43.112.78:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.client1.zuelligpharma.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.client1.zuelligpharma.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.client1.zuelligpharma.com:7051
      - CORE_PEER_LOCALMSPID=client1MSP
      - CORE_OPERATIONS_LISTENADDRESS=peer1.client1.zuelligpharma.com:18051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1.client1.zuelligpharma.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
      - couchdb1.client1.zuelligpharma.com
    volumes:
      - /var/run/:/host/var/run/
      # - /home/azureuser/crypto-config/peer1/msp:/etc/hyperledger/fabric/msp
      # - /home/azureuser/crypto-config/peer1/tls:/etc/hyperledger/fabric/tls
      - /home/azureuser/organizations1/peerOrganizations/client1.zuelligpharma.com/peers/peer1.client1.zuelligpharma.com/msp:/etc/hyperledger/fabric/msp
      - /home/azureuser/organizations1/peerOrganizations/client1.zuelligpharma.com/peers/peer1.client1.zuelligpharma.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 8051:8051
      - 18051:18051
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    networks:
      - test
  couchdb0.client1.zuelligpharma.com:
    container_name: couchdb0.client1.zuelligpharma.com
    image: couchdb:3.1.1
    labels:
      service: hyperledger-fabric
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "5984:5984"
    networks:
      - test
  couchdb1.client1.zuelligpharma.com:
    container_name: couchdb1.client1.zuelligpharma.com
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "6984:5984"
    networks:
      - test
  # cli:
  #   container_name: client_cli
  #   image: hyperledger/fabric-tools:2.2
  #   tty: true
  #   stdin_open: true
  #   dns_search: . #iteration
  #   environment:
  #     - GOPATH=/opt/gopath
  #     - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
  #     #- FABRIC_LOGGING_SPEC=DEBUG
  #     - FABRIC_LOGGING_SPEC=INFO
  #     - CORE_PEER_ID=cli
  #     - CORE_PEER_ADDRESS=104.43.112.78:7051
  #     - CORE_PEER_LOCALMSPID=client1MSP
  #     - CORE_PEER_TLS_ENABLED=true
  #     - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/peer0.client1.zuelligpharma.com/tls/server.crt
  #     - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/peer0.client1.zuelligpharma.com/tls/server.key
  #     - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/peer0.client1.zuelligpharma.com/tls/ca.crt
  #     - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/peer0.client1.zuelligpharma.com/msp
  #   working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
  #   command: /bin/bash
  #   volumes:
  #     - /var/run/:/host/var/run/
  #     - /home/azureuser/peerOrganizations:/opt/gopath/src/github.com/hyperledger/fabric/peer
  #   depends_on:
  #     - peer0.client1.zuelligpharma.com
  #     - peer1.client1.zuelligpharma.com
  #   networks:
  #     - network
